Mr 100 be sn slogin
2021-Techeer-teamC/MATHRONE_Backend pull request #3
Opened 2022-10-19 05:43 UTC by IAGREEBUT

2022-10-19 14:37 UTC, ohhondgi requested changes
궁금한 사항들은 댓글 달았습니다! 소셜 로그인 구현하시느라 고생많으셨습니다 ㅠㅠ

@h01010 
갑자기 햇갈리는점이 있는데,  email을 userId로 변경하는 과정은 이 pr이 머지된 이후에 시작하기로 했었나요?

2022-10-19 14:37 UTC, ohhondgi commented on src/main/java/mathrone/backend/controller/MainPageController.java
> +    public static class SnsLoginController {
이 SnsLoginController는 누락된 코드일까요?? conflict난 code를 살펴보고 있는데 이 코드가 보여서 질문드려요!

2022-10-19 14:37 UTC, ohhondgi commented on src/main/java/mathrone/backend/controller/dto/OauthDTO/OAuthAttributes.java
> +//public class OAuthAttributes {
여기 주석부분들은 현재 프로젝트에 userId가 email이여서 주석으로 일단 처리하신건지 궁금합니다 :)

2022-10-19 14:37 UTC, ohhondgi commented on src/main/java/mathrone/backend/controller/dto/UserSignUpDto.java
> +    public UserSignUpDto(String email, String password, String id) {
이 부분은 AllArgsConstructor annotation 사용했을 때 오류가 떠서 수정하신걸까요?

2022-10-19 14:37 UTC, ohhondgi commented on src/main/resources/keys/application_default_credentials.json
> +{
application_default_credentials파일은 github에 올라가면 안되지 않나요??

2022-11-01 05:07 UTC, IAGREEBUT commented on src/main/java/mathrone/backend/controller/MainPageController.java
> +    public static class SnsLoginController {
앗 네! 원래는 따로 생성하려다가 통일하는게 좋을 것 같아서 userController에 구현하였는데 삭제를 잊은 것 같습니다! 삭제해서 다시 push 하겠습니다! 감사합니다.

2022-11-01 05:11 UTC, IAGREEBUT commented on src/main/java/mathrone/backend/controller/dto/OauthDTO/OAuthAttributes.java
> +//public class OAuthAttributes {
삭제되어야 하는 파일인 것 같습니다!
방식을 이것 저것 하다보니 잔재가 많이 남았네요 ㅎㅎ; 삭제했습니다!

2022-11-01 05:12 UTC, IAGREEBUT commented on src/main/java/mathrone/backend/controller/dto/UserSignUpDto.java
> +    public UserSignUpDto(String email, String password, String id) {
UserSignUpDto를 기존에 사용하던 코드들은 toUser를 이용해서 사용하였는데,
GOOGLE login으로 가입시에는 Password를 알아낼 수 없는 등 toUser를 사용해서 생성하기 어려워서 생성자를 하나 추가해서 사용하는 방식을 이용하였습니다!

2022-11-01 05:14 UTC, IAGREEBUT commented on src/main/resources/keys/application_default_credentials.json
> +{
지금 사용하고 있는 postgre사용 시 비밀번호등을 입력하는 것처럼 
google auth도 비슷한 방식으로 secret키 id등을 입력해야해서 형식만 남겨두었고 키는 올리지 않았습니다! 
사용시 [] <-이 부분에 맞는 키값을 추가해서 쓰셔야해요 (notion첨부)

google.auth.url=[url]
 google.login.url=[url]
 google.redirect.uri=[redirect uri]
 google.client.id=[client_id]
 google.secret=[secret]
 google.auth.scope=[scope]
 google.auth.grantType=[grantType]
 spring.profiles.include=oauth

2022-11-01 06:55 UTC, merged